import React from 'react'
import './index.scss'

const Contact = () => {
    return (
        <div className='contact'>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quam fugit fugiat et rem neque exercitationem, excepturi est eligendi? Quis reprehenderit odit magnam, nam saepe id veritatis dolore animi eum minima dolores quidem voluptas est nisi laborum rem. Nesciunt, consequatur! Ab illum totam adipisci similique dolorem quae vitae quam soluta. Est corporis reiciendis culpa magni cupiditate sit in possimus incidunt provident, fuga labore repellendus ullam, nulla pariatur a voluptatum architecto laudantium, beatae nam perferendis ipsum. Unde illum, ipsa repellendus voluptates, facilis vitae dolor qui architecto quis blanditiis perspiciatis fugit odit praesentium modi, repudiandae temporibus. Ratione totam numquam deleniti quibusdam, distinctio officia quo sit nulla incidunt libero, quae eveniet recusandae suscipit molestiae iure aliquid architecto assumenda ducimus dolorem dicta, iusto aspernatur accusantium sed magnam! Enim voluptates, aperiam reiciendis quas maxime nulla, ex consequatur fuga nesciunt tenetur dolorem nihil debitis dolores excepturi atque minima adipisci illo, quasi eaque optio corrupti cupiditate saepe quod? Suscipit nemo minima quam eveniet illo, animi laborum velit, quaerat, saepe dolorem nam. Corrupti, illo, veritatis placeat quos fugit veniam unde laborum alias et dicta assumenda ducimus aliquid commodi rerum quam odio in quaerat quia quod! Veniam recusandae minima a nostrum repudiandae tenetur illum voluptatem. Obcaecati debitis eveniet soluta architecto vero nihil? Veniam eum illo rem pariatur consequuntur beatae harum perferendis quaerat enim. Inventore soluta cum excepturi quia fugiat perspiciatis eum neque, voluptatum, et molestiae iure vero amet! Iure, unde. Libero, cum pariatur nisi voluptatem doloribus saepe! Fugiat, dignissimos ut dolores architecto culpa perspiciatis, a quam ab deserunt corporis quos rerum tempore rem. Explicabo eum repellendus repellat eveniet molestias cupiditate molestiae quidem aut optio aliquam odio facere provident, quam quod qui omnis iste magnam natus? Saepe eaque doloribus consectetur inventore quis sequi, doloremque praesentium? Modi minus quae nam, minima dolorum perferendis dicta voluptate recusandae. Quae modi cupiditate necessitatibus labore, explicabo dolorum. Natus ducimus iure sint magni sapiente nemo ex quisquam, optio pariatur! Cupiditate dolorem neque molestias? Officia, modi sed nam doloribus maiores voluptates vel qui nihil porro voluptatum laborum libero esse ab necessitatibus corrupti eligendi fuga optio dolor temporibus eos enim voluptatem neque placeat quibusdam? Nisi iste hic libero enim quod ipsum eos natus saepe! Possimus at quae ex repellat ad a quam, minus fugit sunt ratione magni nostrum fugiat iste numquam sequi cumque? Itaque ab ratione quod harum amet tenetur tempore unde porro! Nobis eius architecto eos. Animi praesentium similique aspernatur tempora numquam voluptatibus expedita, cumque corrupti eius deserunt.</p>
        </div>
    )
}

export default Contact